services:
  - type: web
    name: LetsChatFun
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn videoconference.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: videoconference.settings
      - key: PYTHON_VERSION
        value: 3.11
