# Generated by Django 5.1.4 on 2025-05-25 10:50

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoconference_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoconference',
            name='created_by',
        ),
        migrations.AddField(
            model_name='videoconference',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videoconference',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='videoconference',
            name='room_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
